### ISSUE TITLE
No wiki --> OBJECTIVE FUNCTION?

### ISSUE THREAD

**Issue by Ex7reMeFx** [Manevolent/EggCrack#10]
First of all, I wanted to let you guys know that your wiki is down. :)

Secondly, would you mind explaining what the "Objective" option does under the Max threads option?

Thanks for making this tool! Much appreciated. :)

**Comment by Manevolent** [comment]
The objective option allows the cracker to stop prematurely if a certain amount of accounts have been cracked. This is used by users who want the cracker to stop automatically if an objective is met (e.g. running EggCrack within a cron job)

There are other objectives too, accessible from the console mode, for duration, request count, etc.
