### ISSUE TITLE
Running on the commandline

### ISSUE THREAD

**Issue by spideyroc1** [Manevolent/EggCrack#19]
I am buying a linux vps to run a cracker on it, but I want to know if I can use command line with eggcrack 1.8 and what is the syntax, thanks.

**Comment by ClemaX** [comment]
Same here, would be really helpful to have some docs about it :)

**Comment by games647** [comment]
Yes, Eggcrack has as console feature. Just run it with the -console flag. The available arguments can be found [here](https://github.com/Manevolent/EggCrack/blob/master/src/main/java/net/teamlixo/eggcrack/Main.java#L65). 

Sent from mobile

**Comment by ClemaX** [comment]
Thanks, just saw this bit later, problem is it doesn't run without desktop server, I would need something 100% CLI :/

**Comment by Qballl** [comment]
If you get a Linux VPS you should be able to install some sort of vnc server on it, but I would check with your VPS host to make sure.

**Comment by KixStart** [comment]
https://github.com/Manevolent/EggCrack/issues/42
Still the same
