### ISSUE TITLE
Adapt program

### ISSUE THREAD

**Issue by LucasRoot** [Manevolent/EggCrack#2]
I want to adapt this program to another site.
What files can I edit to allow this?

**Comment by Manevolent** [comment]
https://github.com/Manevolent/EggCrack/tree/master/MinecraftPlugin/src/main/java/net/teamlixo/eggcrack/minecraft

This section contains the Minecraft plugin source, I've done all this very similarly to the Bukkit plugin system. The authentication services call back with exceptions with a specific enumerated operation the cracker should then follow.

Unfortunately the cracker does not support highly configurable files like SentryMBA does; if you're looking for a good config-based cracker you might have some success with that program.

**Comment by LucasRoot** [comment]
I dont like MBA
I think I will pay a person to do this for me.
Thanks mate

**Comment by Manevolent** [comment]
I will do it for free, with it being my project. If there's a specific web service others might also be able to use, just let me know and I can try to build a plugin for it

**Comment by LucasRoot** [comment]
Better no, its a special netflix config.
