### ISSUE TITLE
I have this issue, HELP!

### ISSUE THREAD

**Issue by xKOSIUSx** [Manevolent/EggCrack#3]
This is my issue: http://prntscr.com/8pugc6
What can I do?

Regards,
xKOSIUSx

**Comment by Manevolent** [comment]
This is a problem with the layout system I use to build EggCrack. Sometimes it won't correctly compile, which can be quite frustrating. I'll look into this today.

**Comment by xKOSIUSx** [comment]
So i cant use the current version?

**Comment by Manevolent** [comment]
Not at the moment. Within the next hour, a working version will be committed.
