### ISSUE TITLE
Demo Accounts

### ISSUE THREAD

**Issue by urgayxd** [Manevolent/EggCrack#30]
EggCrack still marks demo accounts as working accounts
Just a suggestion, there should be an option to remove the demo accounts.

I don't even now if this project is even active anymore but hopefully you'll read this.

Thanks so much :)

**Comment by Manevolent** [comment]
There is an outstanding issue with the project that follows an ongoing issue with the authentication API which has caused the cracker to become obsolete. I suggest finding another project which has a solution for this or waiting until someone forks this repository with a solution implemented.
