### ISSUE TITLE
This is a question.

### ISSUE THREAD

**Issue by xKOSIUSx** [Manevolent/EggCrack#4]
This isnt an issue but a question.
How long will the current program work on 5k accounts, 10k passwords and 3k proxies

**Comment by Manevolent** [comment]
That's 50,000,000 attempts. It depends on how many attempts/sec your 3k proxies get. Each proxy is internally limited to 0.05 requests/sec to create 1 request per 20 seconds (Limitations put on login). This adds up to a maximum of 150 attempts/sec, or 333,333 seconds, which is 92 hours.

You're probably going to need more proxies to get more attempts/sec.
