### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by LucasRoot** [Manevolent/EggCrack#5]
Sorry to annoy again.
How can I use command line in the program?

Alredy tried: java -jar EggCrack.jar proxies=/home/proxy.txt
java -jar EggCrack.jar -proxies=/home/proxy.txt

**Comment by MaggieMoo** [comment]
java -jar EggCrack.jar -usernames usernames.txt -passwords passwords.txt -proxies proxies.txt -outputFile output.txt

**Comment by LucasRoot** [comment]
Thanks, I will text later because I cant right now.
Can you recommend me a VPN, please?

**Comment by LucasRoot** [comment]
I want to buy a VPN to crack them

**Comment by LucasRoot** [comment]
And if I want to use the check mode?

**Comment by Manevolent** [comment]
Normal username/password list cracking is done through the following arguments:

```
 java -jar EggCrack.jar -usernames usernames.txt -passwords passwords.txt -proxies proxies.txt -outputFile output.txt
```

If you were to check "output.txt", you would instead use the following:

```
 java -jar EggCrack.jar -check output.txt -proxies proxies.txt -outputFile output2.txt
```
