### ISSUE TITLE
0 attempts per second / super slow eggcrack

### ISSUE THREAD

**Issue by dumbninja22** [Manevolent/EggCrack#7]
Hi,

Why do I keep getting 0 attempts per second? I tried all sorts of proxies, from Elite, to anonymous, to ones that were checked, to 15k that weren't, but I still get 0 to 2 attempts per second, usually 0.

Any ideas?

**Comment by LucasRoot** [comment]
Try the Egg.Crack 1.8

**Comment by NoahWL1** [comment]
Yeah, I'm getting this too.  It jumps around from 0 to 1 or 2.  At first I thought it was the proxies I was using, but after trying to many different Elite proxies and seeing the problems others are having, I don't think it's that anymore.

**Comment by Manevolent** [comment]
I'm consolidating discussion onto issue #15:
https://github.com/Manevolent/EggCrack/issues/15
