### ISSUE TITLE
Java Error When Opening

### ISSUE THREAD

**Issue by geOGRE69** [Manevolent/EggCrack#9]
I've downloaded eggcrack 2.0 but when I open it it comes up with this message http://prntscr.com/8xeo1z Followed by this message once I pressed ok http://prntscr.com/8xeo4f 
I have done nothing to any of the files I simply opened eggcrack and this happened. I have updated to the latest java and it still hasn't worked. If you could tell me what I'm doing wrong that'd be great. Thank you
-George

**Comment by Manevolent** [comment]
You'll need to run the cracker from the console and let me know what exception it's printing to the console, the information provided gives me only a general idea where the problem could be.

**Comment by Pinkcommando** [comment]
Hey George,
I had the same problem, try moving the EggCrack-master from the .zip folder to your desktop then open it from the desktop.
![dsadasd](https://cloud.githubusercontent.com/assets/15956766/11318879/1ebdbba0-9032-11e5-8fbc-cb1bc7ce6c48.png)
